version: "3.3"

services:
  db:
    image: postgres
    restart: always
    container_name: athens_db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: athens
    ports:
      - ${DB_PORT}:5432

  app:
    build: .
    restart: always
    container_name: athens_app
    ports:
      - 127.0.0.1:${WEB_PORT}:5000
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
    environment:
      - FLASK_APP=wsgi:app
      - FLASK_ENV=production
      - FLASK_DEBUG=0

volumes:
  db_data:
